apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
      - name: task-tracker
        image: task-tracker:latest  # Use the name of your local image
        ports:
        - containerPort: 40
